# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Mo Tiwari
email: motiwari at institution name + gTLD
description: >-
  Mo Tiwari's webpage, projects, biography, resume, and FAQ
baseurl: ""
url: "https://motiwari.github.io"

github_username: motiwari
facebook: https://www.facebook.com/mtiwari
linkedin: https://www.linkedin.com/in/motiwari
website: motiwari.com

urls:
    - text: Home
      url: /
      display: True
    - text: Biography
      url: /biography/
      display: True
    # - text: Projects
    #   url: /projects/
    # - text: Publications and Talks
    #   url: /refs/
    - text: Résumé
      url: /resume.pdf
      display: True
    - text: CV
      url: /cv/
    # - text: Coursework
    #   url: /coursework/
    - text: FAQ
      url: /faq/
      display: True
    - text: Feedback
      url: /feedback/
      display: True

author_logo: profile.png
author: Mo Tiwari
author_bio: >-
  Hi! I'm currently a Ph.D. student in Computer
  Science at Stanford University, advised by
  <a href="http://robots.stanford.edu/personal.html">Sebastian Thrun</a> (funding advisor) and
  <a href="https://stanford.edu/~cpiech/bio/index.html">Chris Piech</a>.
author_bio2: >-
  I have an unconventional path to the Ph.D.
  program in that I worked for 4 years in between my undergraduate and graduate
  studies. I have an eclectic career spanning particle physics,
  quantum computation, finance, cybersecurity, virtual and augmented reality,
  artificial intelligence, machine learning, and healthcare -- largely because
  I love learning new things about math, physics, statistics, and computer
  science!
author_bio3: >-
  If you're interested in collaborating, please get in touch -- especially
  if you're at Stanford!
author_location: Stanford, CA
author_website_url: "http://motiwari.com"

author_work_experiences:
    - company_name: Facebook (and Oculus)
      company_logo: facebook.png
      dates: 2015-2017
      designation: Software Engineer, Technical Lead - Security
      description:
        - >-
          Technical lead of the 4-person team building ThreatExchange
          (fb.me/TX), Facebook’s platform for sharing cybersecurity
          information
        - >-
          Led product and feature development through 5 major releases
          that grew the number of enterprise customers from 92 to 500+
        - >-
          Managed 3 interns who received and accepted fulltime offers
      visibility: true
    - company_name: Expanse (previously known as Qadium)
      company_logo: expanse.png
      dates: 2014 - 2015
      designation: Software Engineer and Security Researcher
      description:
        - >-
          Performed the first systematic, continuous, and Internet-scale
          capture and analysis of device data and security vulnerabilities
        - >-
          Built backend and frontend infrastructure to help analysts
          understand terabytes of prostitution advertisements and
          uncover human trafficking
        - >-
          Work indirectly led to dozens of arrests of traffickers and
          hundreds of victims saved
      visibility: true
    - company_name: DRW
      company_logo: drw.png
      dates: Summer 2013
      designation: Researcher
      description:
        - >-
          Supported the highest-performing traders with quantitative research
        - >-
          Created valuation models for various financial instruments,
          such as interest rate swaps and swaptions
      visibility: true

author_education_details:
    - college_logo: stanford.png
      college_name: Stanford University, GPA&#58; 4.2
      college_degree: Ph.D. in Computer Science
      description: >-
        Focusing on artificial intelligence and machine
        learning methods, with applications to healthcare. Also
        completed the M.S. degree during the Ph.D.
      visibility: true
    - college_logo: caltech.png
      college_name: Caltech, GPA&#58; 4.0+
      college_degree: B.S. in Mathematics, B.S. in Physics (double major)
      description: >-
        I double majored in Mathematics and Physics and graduated in
        the top 10% of my class (top 20), with Honors. I was even
        ranked 3rd for most of my time there!
      visibility: true
    - college_logo: columbia.png
      college_name: Columbia University, GPA&#58; 4.1
      college_degree: B.A. in Mathematics, B.A. in Physics (incomplete)
      description: >-
        While I loved Columbia and living in NYC, I transferred to
        Caltech after my freshman year.
      visibility: true

accomplishments:
  - In 2017, I was admitted to Stanford's Ph.D. program in Computer Science and Berkeley's Ph.D. program in EECS (among others).
  - In 2015, I was admitted to MIT's Ph.D. program in Physics (among others) (I declined).
  - >-
    In 2013, I graduated with Honors in the top 10% and top 20 students
    from Caltech, with a double major in mathematics and physics.
  - >-
    In 2010, I was one of 7 transfer students accepted to Caltech.
  - >-
    In 2009, I won third place in category at the Intel ISEF, an international
    competition for high school students.

# social links
github_username:  motiwari
linkedin_username: motiwari
facebook_username: mtiwari
twitter_username: motiwari

# for comments using disqus
disqus_shortname: motiwari

# formspree (contact form)
formspree_email: motiwari@stanford.edu

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-156050084-1

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_accomplishments: true
show_namespace_collision: true

# Build settings -- do not modify
theme: devlopr

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
  - jekyll-redirect-from
# - jekyll-archives

# pagination of posts
paginate_path: "/projects/page:num/"
paginate: 8
per_page: 4

# minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

collections:
 - products

# algolia search
# algolia:
#   application_id: D9WA1YKTRQ
#   index_name: project_posts # You can replace that with whatever name you want
#   files_to_exclude: []
#   nodes_to_index: 'article'
#   search_only_api_key: REDACTED

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
