---
title: Mo Tiwari
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: false
  uploads:
    title: Uploads
    output: true
email: motiwari at institution name + gTLD
description: Mo Tiwari's webpage, projects, biography, resume, and FAQ
baseurl: ''
url: https://motiwari.github.io
github_username: motiwari
facebook: https://www.facebook.com/mtiwari
linkedin: https://www.linkedin.com/in/motiwari
website: motiwari.com
urls:
- text: Home
  url: "/"
  display: true
- text: Biography
  url: "/biography/"
  display: true
- text: Résumé
  url: "/resume.pdf"
  display: true
- text: Projects
  url: "/projects"
- text: CV
  url: "/cv/"
- text: Publications and Talks
  url: "/pubs/"
  display: true
- text: Coursework
  url: "/coursework/"
- text: FAQ
  url: "/faq/"
  display: true
- text: Feedback
  url: "/feedback/"
  display: true
author_logo: profile.png
author: Mo Tiwari
author_bio: Hi! I'm currently a Ph.D. student in Computer Science at Stanford University,
  advised by <a href="http://robots.stanford.edu/personal.html">Sebastian Thrun</a>.
author_bio2: I have an unconventional path to the Ph.D. program in that I worked for
  4 years in between my undergraduate and graduate studies. I have an eclectic career
  spanning particle physics, quantum computation, finance, cybersecurity, virtual
  and augmented reality, artificial intelligence, machine learning, and healthcare
  -- largely because I love learning new things about math, physics, statistics, and
  computer science!
author_bio3: For a more formal biography, check out <a href="/biography/">my biography</a>. If you're interested in collaborating, please get in touch -- especially
  if you're at Stanford!
author_location: Stanford, CA
author_website_url: http://motiwari.com
author_work_experiences:
- company_name: Facebook (and Oculus)
  company_logo: facebook.png
  dates: 2015-2017
  designation: Software Engineer, Technical Lead - Security
  description:
  - Technical lead of the 4-person team building ThreatExchange (fb.me/TX), Facebook’s
    platform for sharing cybersecurity information
  - Led product and feature development through 5 major releases that grew the number
    of enterprise customers from 92 to 500+
  - Managed 3 interns who received and accepted fulltime offers
  visibility: true
- company_name: Expanse (previously known as Qadium)
  company_logo: expanse.png
  dates: 2014 - 2015
  designation: Software Engineer and Security Researcher
  description:
  - Performed the first systematic, continuous, and Internet-scale capture and analysis
    of device data and security vulnerabilities
  - Built backend and frontend infrastructure to help analysts understand terabytes
    of prostitution advertisements and uncover human trafficking
  - Work indirectly led to dozens of arrests of traffickers and hundreds of victims
    saved
  visibility: true
- company_name: DRW
  company_logo: drw.png
  dates: Summer 2013
  designation: Researcher
  description:
  - Supported the highest-performing traders with quantitative research
  - Created valuation models for various financial instruments, such as interest rate
    swaps and swaptions
  visibility: true
author_education_details:
- college_logo: stanford.png
  college_name: Stanford University, GPA&#58; 4.2
  college_degree: Ph.D. in Computer Science
  description: Focusing on artificial intelligence and machine learning methods, with
    applications to healthcare. Also completed the M.S. degree during the Ph.D.
  visibility: true
- college_logo: caltech.png
  college_name: Caltech, GPA&#58; 4.0+
  college_degree: B.S. in Mathematics, B.S. in Physics (double major)
  description: I double majored in Mathematics and Physics and graduated in the top
    10% of my class (top 20), with Honors. I was even ranked 3rd for most of my time
    there!
  visibility: true
- college_logo: columbia.png
  college_name: Columbia University, GPA&#58; 4.1
  college_degree: B.A. in Mathematics, B.A. in Physics (incomplete)
  description: While I loved Columbia and living in NYC, I transferred to Caltech
    after my freshman year.
  visibility: true
accomplishments:
- In 2017, I was admitted to Stanford's Ph.D. program in Computer Science and Berkeley's
  Ph.D. program in EECS (among others).
- In 2015, I was admitted to MIT's Ph.D. program in Physics (among others) (I declined).
- In 2013, I graduated with Honors in the top 10% and top 20 students from Caltech,
  with a double major in mathematics and physics.
- In 2010, I was one of 7 transfer students accepted to Caltech.
- In 2009, I won third place in category at the Intel ISEF, an international competition
  for high school students.
linkedin_username: motiwari
facebook_username: mtiwari
twitter_username: motiwari
disqus_shortname: motiwari
formspree_email: motiwari@stanford.edu
markdown: kramdown
highlighter: rouge
permalink: pretty
google_analytics: UA-156050084-1
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_accomplishments: true
show_namespace_collision: true
theme: devlopr
plugins:
- jekyll-paginate
- jekyll-gist
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-algolia
- jekyll-redirect-from
paginate_path: "/projects/page:num/"
paginate: 12
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
  endings: all
  ignore:
    envs:
    - development
